name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  FLUTTER_VERSION: "3.27.3"
jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - name: Run lint and format check for all solution projects
        run: |
          for d in $(find . -type d -name "*solution*"); do
            if [ -f "$d/pubspec.yaml" ]; then
              echo "Checking project in $d"
              cd "$d"
              flutter pub get
              dart analyze . --fatal-infos
              dart format $(find lib -name "*.dart" -not \( -name "*.*freezed.dart" -o -name "*.*g.dart" \) ) --set-exit-if-changed
              cd -
            fi
          done

  unit_and_widget_tests:
    needs: lint
    name: Unit and Widget tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - name: Run tests for all solution projects
        run: |
          for d in $(find . -type d -name "*solution*"); do
            if [ -f "$d/pubspec.yaml" ]; then
              echo "Testing project in $d"
              cd "$d"
              flutter pub get
              flutter test --exclude-tags=golden
              cd -
            fi
          done 